// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1wP-5QxDpTAQOsS2UcDvRXr-0i4Lhv3A',
    appId: '1:1044490066442:web:5f61aaf91775785c1f1df3',
    messagingSenderId: '1044490066442',
    projectId: 'bwapesawattest',
    authDomain: 'bwapesawattest.firebaseapp.com',
    storageBucket: 'bwapesawattest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA37NzGFm_T0YKaF-6VTIsczxWevTGHDds',
    appId: '1:1044490066442:android:1f49a4b0d25e12301f1df3',
    messagingSenderId: '1044490066442',
    projectId: 'bwapesawattest',
    storageBucket: 'bwapesawattest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-bDO_SGsMVOb331M40lQVy0MJ3Ar4xGM',
    appId: '1:1044490066442:ios:6cbe4b38e6bfbf511f1df3',
    messagingSenderId: '1044490066442',
    projectId: 'bwapesawattest',
    storageBucket: 'bwapesawattest.appspot.com',
    iosClientId: '1044490066442-41qvqjt9q8bmc9jeuk28m0vj9oqlrnss.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwaPesawats',
  );
}
